### ISSUE TITLE
只允许特定账户调用

### ISSUE THREAD

**Issue by Sefank** [yoyicue/omegat-tencent-plugin#4]
接口调用失败，提示：
`Message:请求被拒绝，该接口只允许特定账户调用。`

**Comment by SpecterHi** [comment]
您好，安装了最新的OmegaT 4.2.0版本，没有发现内建翻译君，所以还是安装了此插件。
然后同样遇到了上述接口调用失败的提示。
![image](https://user-images.githubusercontent.com/2437251/60485035-29cce280-9cce-11e9-9807-443d8e4740bf.png)

**Comment by xflcx1991** [comment]
问题是已经解决了的。用现有代码按照readme编译得到的jar就可以用。
